version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ruflin/elastica
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.3
    - 6.1.4
