language: php
php:
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=search_elastic
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - stable7

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

script:
  # Test lint
  - cd ../core/apps/$APP_NAME
  - find . -name \*.php -exec php -l "{}" \;

matrix:
  fast_finish: true
  include:
     - php: 5.6
       env: CORE_BRANCH=stable10
     - php: 7.0
       env: CORE_BRANCH=stable10
