language: php
php:
  - 5.6
  - 7.0

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=search_elastic
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - stable7

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

script:
  # Test lint
  - cd ../core/apps/$APP_NAME
  - find . -name \*.php -exec php -l "{}" \;

  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"

matrix:
  include:
    - php: 7.0
      env: DB=mysql
    - php: 7.0
      env: DB=pgsql
    - php: 5.6
      env: DB=oracle
  fast_finish: true
