<?php
/**
 * ownCloud
 *
 * @author Michael Barz <mbarz@owncloud.com>
 * @copyright (C) 2019 ownCloud GmbH
 * @license ownCloud Commercial License
 *
 * This code is covered by the ownCloud Commercial License.
 *
 * You should have received a copy of the ownCloud Commercial License
 * along with this program. If not, see
 * <https://owncloud.com/licenses/owncloud-commercial/>.
 *
 */

namespace OCA\Search_Elastic\Tests\Unit\Hooks;

use OCA\Search_Elastic\Hooks\Files;
use Test\TestCase;

/**
 * Class TestFiles
 *
 * @package OCA\Search_Elastic\Tests\Unit\Hooks
 */
class TestFiles extends TestCase {
	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	/**
	 * DataProvider Exclude Paths
	 *
	 * @return array
	 */
	public function excludeProvider() {
		return [
			'normal file' => ['/admin/files/Testfile', false],
			'file in subfolder' => ['/admin/files/Sub1/Folder/Testfile.zip', false],
			'thumbnail' => ['/admin/thumbnails/Testfile2', true],
			'avatars' => ['/avatars/12', true],
			'no user folder' => ['/Testfile.txt', true],
			'wrong path' => ['//user/files/folder/testfile', false],
			'versions' => ['/user01/versions/Testfile.txt', true],
			'trashbin' => ['/user01/trashbin/Testfile.txt', true]
		];
	}

	/**
	 * Test The Helper Function
	 *
	 * @dataProvider excludeProvider
	 *
	 * @param string $path
	 * @param bool $expected
	 *
	 * @return void
	 */
	public function testExcludeIndex($path, $expected) {
		$filesProcessor = new Files();
		self::assertEquals($expected, $filesProcessor->excludeIndex($path));
	}
}
