<?php
/**
 * @author Michael Barz <mbarz@owncloud.com>
 *
 * @copyright Copyright (c) 2019, ownCloud GmbH
 * @license GPL-2.0
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 */

namespace OCA\Search_Elastic\Tests\Unit\Hooks;

use OCA\Search_Elastic\Hooks\Files;
use Test\TestCase;

/**
 * Class TestFiles
 *
 * @package OCA\Search_Elastic\Tests\Unit\Hooks
 */
class TestFiles extends TestCase {
	public function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	/**
	 * DataProvider Exclude Paths
	 *
	 * @return array
	 */
	public function excludeProvider() {
		return [
			'normal file' => ['/admin/files/Testfile', false],
			'file in subfolder' => ['/admin/files/Sub1/Folder/Testfile.zip', false],
			'thumbnail' => ['/admin/thumbnails/Testfile2', true],
			'avatars' => ['/avatars/12', true],
			'no user folder' => ['/Testfile.txt', true],
			'wrong path' => ['//user/files/folder/testfile', false],
			'versions' => ['/user01/versions/Testfile.txt', true],
			'trashbin' => ['/user01/trashbin/Testfile.txt', true]
		];
	}

	/**
	 * Test The Helper Function
	 *
	 * @dataProvider excludeProvider
	 *
	 * @param string $path
	 * @param bool $expected
	 *
	 * @return void
	 */
	public function testExcludeIndex($path, $expected) {
		$filesProcessor = new Files();
		self::assertEquals($expected, $filesProcessor->excludeIndex($path));
	}
}
